WilburZBlog/WilburZBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('blog/', include('blog.urls', namespace='blog')),    # 当浏览器输入http://127.0.0.1:8000/blog/则跳转至blog应用urls中
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace='article')),
    path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
]

WilburZBlog/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'
urlpatterns = [
    # path('login/', views.user_login, name='user_login'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login2.html'), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),
    path('register/', views.register, name='user_register'),
    path('password-change/', auth_views.PasswordChangeView.as_view(
        template_name="account/password_change_form.html", success_url="/account/password-change-done/"),
         name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(
        template_name="account/password_change_done.html"), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name="account/password_reset_form.html", email_template_name="account/password_reset_email.html",
        success_url='/account/password-reset-done/'), name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(
        template_name="account/password_reset_done.html"), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="account/password_reset_confirm.html", success_url='/account/password-reset-complete/'),
         name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name="account/password_reset_complete.html"),
         name="password_reset_complete"),
    path('my-information/', views.myself, name="my_information"),
    path('edit-my-information/', views.myself_edit, name="edit_my_information"),
    path('my-image/', views.my_image, name="my_image"),
]

WilburZBlog/article/urls.py
from django.urls import path, re_path
from . import views, list_views

app_name = 'article'

urlpatterns = [
    path('article-column/', views.article_column, name='article_column'),
    path('rename-column/', views.rename_article_column, name='rename_article_column'),
    path('del-column/', views.del_article_column, name='del_article_column'),
    path('article-post/', views.article_post, name='article_post'),
    path('article-list/', views.article_list, name='article_list'),
    re_path('artilce-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name='article_detail'),
    path('del-article/', views.del_article, name='del_article'),
    path('redit-article/<int:article_id>/', views.redit_article, name='redit_article'),
    path('list-article-titles/', list_views.article_titles, name='article_titles'),
    path('article-content/<int:id>/<slug:slug>/', list_views.article_detail, name='article_content'),
    path('list-article-titles/<username>/', list_views.article_titles, name="author_articles"),
    path('list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles, name="author_articles"),
    path('like-article/', list_views.like_article, name='like_article')
]

WilburZBlog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog_title, name='blog_title'),     # 当跟路由跳转到此应用urls是，则执行views.blog_title函数，渲染至网页
    path('<int:article_id>/', views.blog_article, name='blog_article'),  # 将title.html得到的文章Id传给blog_article函数，从而获得相应点击超链接的文章内容
]

WilburZBlog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-cn">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=devce-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    </head>
    <body>
        {% include "header.html" %}
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        {% include "footer.html" %}
        {% block javascript %}{% endblock %}
    </body>
</html>

WilburZBlog/templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right www.itdiffer.com</p>
</div>

WilburZBlog/templates/header.html
{% load static %}
<div class="container">
  <nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static '/images/logo.png' %}" width="100px">
      </a>
    </div>
    <div>
      <ul class="nav navbar-nav" role="navigation">
        <li><a href="{% url 'home' %}">HOME</a></li>
        <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
        <li><a href="{% url 'article:article_titles' %}">文章</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
        {% if user.is_authenticated %}
        <li class="dropdown" style="margin-top:8px">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown">
            {{ user.username }}
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
            <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
            <li><a href="{% url 'article:article_column' %}">后台管理</a></li>
          </ul>
        </li>
        <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
        <li><a href="{% url 'account:user_register' %}">Sign up</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>  <!-- 引导装入程序 -->

WilburZBlog/templates/home.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}

<div class="text-center">
  <h1>WELLCOME YOU</h1>
  <h3>Life is short.You need Python</h3>
  <h2>Django makes it easier to build better web apps more quickly and with less code.</h2>
  {% load static %}
  <img src="{% static 'images/book.jpg' %}">
</div>

{% endblock %}

WilburZBlog/templates/paginator.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}    
    <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>